### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by ai** [storeon/localstorage#1]
You need to copy docs best practices from [Storeon](https://github.com/storeon/storeon).

1. Add short and clear project description (also use it in `package.json` and GitHub repo).
2. Add size
3. Add the link to Storeon
4. Add more example. Maybe we should use `path` option in the main example because most of the users will use it.

**Comment by polemius** [comment]
I've update the readme file. I've added the exmple from storeon readme. And show how the module can save the state to local storage. 

Should I add something else?

**Comment by ai** [comment]
1. It will be better to be more clear what it does.

> The 185 bytes module for storeon to store and sync state to `localStorage`. It restores state from `localStorage` during page loading and saves state on every change.

2. We should merge Usage and EXAMPLE. Why do we need 2 different examples?

3. We should improve the example. `count` is too abstract. Show the real data which should be stored in localStorage.

4. We should clean example. Right now example contains much unnecessary information (we do not need to copy Storeon docs).

**Comment by polemius** [comment]
Thank you. I've update the docs. Now I add the example where I store the form data in state. And also add the gif screen record how it is working. What do you think abouth this sort of example?

**Comment by ai** [comment]
I think it will be better to move 

```js
import useStoreon from 'storeon/react';
import StoreContext from 'storeon/react/context'
```

into second code example. In the real project, it will be separated files.

**Comment by ai** [comment]
The second thing, you should use `persistState('name')` in an example. It is good practice to have white-list of fields.

**Comment by ai** [comment]
Third thing, we can remove `App` from the example. `@storeon/localstorage` should know how to use Storeon.

**Comment by ai** [comment]
```js
const Form = () => {
const { dispatch, name } = useStoreon('name')
```

You forgot indent here

**Comment by ai** [comment]
I also recommend showing `npm` example here https://github.com/storeon/localstorage#installation

Yarn users mostly know how to replace `npm` to `yarn`. But JS junior developers will not understand what to do here.

However, it is up to you.

**Comment by ai** [comment]
`storeon` → `Storeon`

**Comment by polemius** [comment]
Thank you for your suggestions. I have updated the readme file.
