### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by ai** [storeon/localstorage#10]
Tests are very important for any JS open source.

There are a lot of localStorage mocks in npm for testing your module.

Also, you can make a demo test to be sure that everything works in a real browser. Here is how we made it in Storeon:

https://github.com/storeon/storeon/tree/master/test/demo
https://github.com/storeon/storeon/blob/master/package.json#L19

**Comment by polemius** [comment]
Thanks for the links
I've add the multiple unit tests. And the next step is add the demo to check it in real browser.

**Comment by polemius** [comment]
Ok. Now I've added the demo page. I copy it from Storeon repo and change a little bit and I hope you don't mind.
