### ISSUE TITLE
ES2015+ syntax used since 0.10

### ISSUE THREAD

**Issue by L2jLiga** [storeon/localstorage#29]
In 0.10 async/await statements were added, this statements from are ES2015+ but library itself written in ES5 style, is it okay?

I saw #9, so in case this library uses new ES features it need to update docs I assume 🤔

**Comment by polemius** [comment]
@L2jLiga You are right 👍  Thank you for pointing it out. Fixed in new `0.11.0` version

**Comment by L2jLiga** [comment]
Thanks!
