### ISSUE TITLE
Server-side rendering compatibility

### ISSUE THREAD

**Issue by rayriffy** [storeon/localstorage#36]
Details https://github.com/storeon/storeon/issues/103#issuecomment-635360026

**Comment by polemius** [comment]
Thanks 👍 
Maybe we can change something in packages code to make it compatible with SSR? What do you think?

**Comment by rayriffy** [comment]
#### Apologise for my bad English explanation.

Server-side rendering is being used just for render static HTML string with **no browser**, this means there's no `window` being defined which means `localstorage` will not be used by SSR anyway since there're just one-time job.

The solution is to detect that `window` is undefined or not inside `persistState` function. If it is then, mock as empty plugin. Otherwise, do a normal operation.

**Comment by polemius** [comment]
> The solution is to detect that window is undefined or not inside persistState function. If it is then, mock as empty plugin. Otherwise, do a normal operation.

Sounds ok for me. Do you want send a PR?
