### ISSUE TITLE
Rehydration complete callback

### ISSUE THREAD

**Issue by sergeylaptev** [storeon/localstorage#40]
Hello! I want to render my react-native app content only after rehydration completed how can I achieve this? The `event` isn't exposed and no callback provided either.

**Comment by polemius** [comment]
Hello, after rehydration you don't have a rerender? It should rerender automatically

**Comment by sergeylaptev** [comment]
Having re-render isn't enough, I want to make some refetching actions after it's done.

**Comment by polemius** [comment]
Refetching from store? I am sorry, I could not understand. Could you please show some example?
