### ISSUE TITLE
Rename project to @storeon/localstorage

### ISSUE THREAD

**Issue by ai** [storeon/localstorage#5]
Your module is great and should be official

1. Apply invite to GitHub `storeon` organization.
2. Move repo under `github.com/storeon/localstorage`
3. Apply invite to npm organization.
4. Change the name in `package.json` to `@storeon/localstorage`
5. Release under a new name.
6. Mark old npm package as deprecated

**Comment by polemius** [comment]
I did all steps besides the rename repository to `localstorage`. Looks like I have no right to do it. Can you check it?

**Comment by ai** [comment]
I renamed to project and made you an admin

**Comment by ai** [comment]
I also changed GitHub URL https://github.com/storeon/localstorage/commit/cb52c2fda415f341630eafdd6880254fa9b92706
