### ISSUE TITLE
Made a policy about old browser support

### ISSUE THREAD

**Issue by ai** [storeon/localstorage#9]
Right now you use a lot of ES6 feature like object destructors.

In another hand, you do not use many useful ES6 syntax sugars like arrow functions.

I think you should be consistent. If you do not want to support IE, Opera Mini, and Chinese browsers, you should add Babel help to docs (for users who still need to support). I do not support it, because Storeon core and this module will have different supported browsers, which is not cool for the official module. Hoverer, it is your choice.

**Comment by ai** [comment]
Here is how we mention that you need `Object.assign` polyfill https://github.com/storeon/storeon#install

**Comment by polemius** [comment]
I'm not sure that I'm undestanding this correctly. Can you help me please. The Storeon core is supporting IE, Opera Mini and Chinese browsers? 
To be consistent with Storeon core should I use ES6 feature?

**Comment by ai** [comment]
> The Storeon core is supporting IE, Opera Mini and Chinese browsers?

Yes

> To be consistent with Storeon core should I use ES6 feature?

Nope. The question is different:

1. If you want to ignore IE, Opera Mini, and Chinese browsers, you need to use more ES6 features. In this case, you need to add “How to compile the library with Babel for IE” to docs.
2. If you want to be consistent with Storeon core, you need to use only ES5 syntax.

**Comment by polemius** [comment]
Ok, thanks. Now I see :) I will update this module to only ES5 syntax

**Comment by polemius** [comment]
I've updated the module to use only ES5 syntax and reduce the size 👍
